version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=urlshortener
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password

  url-shortener:
    container_name: urlshortener-container
    restart: always
    image: urlshortener
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3307
    depends_on:
      - mysqldb
